sudo: required

services:
   - docker

script: 
   - chmod + x build.sh
   - ./build.sh

before_deploy:
   - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

deploy:
   - provider: script
     script: chmod + x push.sh &&./push.sh
     on:
        branch: $TRAVIS_BRANCH